In [6]:
import json
import os
import pandas as pd

# file_path = os.path.join("conceptual_model", "aiod_model.json")
file_path = os.path.join("conceptual_model", "ontology_data_with_inheritance.json")

with open(file_path, "r") as f:
    conceptual_model = json.load(f)

In [4]:
missing_entities_df = pd.read_csv("comparision_results_noinheritance/missing_entities.csv")
extra_entities_df = pd.read_csv("comparision_results_noinheritance/extra_entities.csv")
missing_properties_df = pd.read_csv("comparision_results_noinheritance/missing_properties.csv")
extra_properties_df = pd.read_csv("comparision_results_noinheritance/extra_properties.csv")

In [27]:
missing_properties_df
# extra_properties_df

,Entity,Property 1,Property 2,Property 3,Property 4,Property 5,Property 6,Property 7,Property 8,Property 9,Property 10,Property 11,Property 12,Property 13,Property 14,Property 15
0,person,member_of,languages,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,aiodconcept,sameas,relevant_link,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mlmodel,training_status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,distribution,date_modified,has_computational_requirement,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,aiodentry,entry_published,content,modified,entry_created,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,organisation,number_of_employees,turnover,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,computationalasset,pricing_scheme,os,kernel,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,service,provider,service_category,service_type,conditions,use_case_example,coverage,prerequisites,service_status,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,experiment,uses_dataset,exemplary_execution_settings,uses_model,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,educationalresource,taught_by,cost,end_date,enrollment_start_date,qualification,offered_by,offered_via,prerequisite_knowledge,uses_resource,enrollment_end_date,under_classification,learning_mode,schedule,expected_outcome,start_date
10,airesource,location,part_of,business_sector,documented_in,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,dataset,pid,variable_measured,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,publication,has_issn,has_isbn,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,event,duration,event_mode,project,event_status,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,runnabledistribution,deployment_process,compilation_time_msec,other_dependency,deployment_time_msec,compilation_process,software_dependency,execution_time_msec,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,project,total_cost_euros,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,aiasset,date_created,applies,licence,pricing,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [28]:
df_combined = pd.concat([missing_properties_df.iloc[10], extra_properties_df.loc[14]], axis=1)
df_combined.columns = ["Missing", "Extra"]
df_combined.dropna(how="all")

                     Missing                         Extra
Entity            airesource                    airesource
Property 1          location                    is_part_of
Property 2           part_of                  date_deleted
Property 3   business_sector             relevant_resource
Property 4     documented_in         aiod_entry_identifier
Property 5               NaN                ai_resource_id
Property 6               NaN                   relevant_to
Property 7               NaN                       same_as
Property 8               NaN        ai_resource_identifier
Property 9               NaN                 relevant_link
Property 10              NaN                          type
Property 11              NaN             scientific_domain
Property 12              NaN                          note
Property 13              NaN        description_identifier
Property 14              NaN              application_area
Property 15              NaN                      platform
Property 16              NaN                       creator
Property 17              NaN                    identifier
Property 18              NaN  platform_resource_identifier
Property 19              NaN             industrial_sector
Property 20              NaN                date_published

In [29]:
for i in range(len(conceptual_model["classes"])):
    if conceptual_model["classes"][i]["name"] == "AIResource":
        print(i)
        break

conceptual_model["classes"][i]

18

{'name': 'AIResource',
 'equivalent_classes': ['Resource'],
 'direct_properties': [{'name': 'documented_in',
   'domain': ['AIResource'],
   'range': ['KnowledgeAsset'],
   'annotations': {'comment': 'A Knowledge Asset describing and documenting the given resource.',
    'label': 'documented in'},
   'equivalent_properties': []},
  {'name': 'research_area',
   'domain': ['AIResource'],
   'range': ['ResearchArea'],
   'annotations': {'comment': 'A research area under which the research problems remedied by the resource fall.',
    'label': 'research area'},
   'equivalent_properties': []},
  {'name': 'media',
   'domain': ['AIResource'],
   'range': ['Multimedia'],
   'annotations': {'comment': 'An image depicting or associated with the resource.',
    'label': 'media'},
   'equivalent_properties': []},
  {'name': 'name',
   'domain': ['AIResource'],
   'range': ['str'],
   'annotations': {'comment': 'A name given to the resource.',
    'label': 'name'},
   'equivalent_properties': []},
  {'name': 'aiod_entry',
   'domain': ['AIResource'],
   'range': ['AIoDEntry'],
   'annotations': {'comment': None, 'label': 'aiod entry'},
   'equivalent_properties': []},
  {'name': 'location',
   'domain': ['AIResource'],
   'range': ['Location'],
   'annotations': {'comment': None, 'label': 'location'},
   'equivalent_properties': ['atLocation']},
  {'name': 'business_sector',
   'domain': ['AIResource'],
   'range': ['BusinessSector'],
   'annotations': {'comment': 'An industrial sector where a resource is or can be of use (possibly in the context of a larger framework or initiative).',
    'label': 'business sector'},
   'equivalent_properties': []},
  {'name': 'part_of',
   'domain': ['AIResource'],
   'range': ['AIResource'],
   'annotations': {'comment': 'A resource that is included as a part/component of this resource.',
    'label': 'part of'},
   'equivalent_properties': []},
  {'name': 'description',
   'domain': ['AIResource'],
   'range': ['str'],
   'annotations': {'comment': 'A usually short informative text on the resource.',
    'label': 'description'},
   'equivalent_properties': []},
  {'name': 'keyword',
   'domain': ['AIResource'],
   'range': ['str'],
   'annotations': {'comment': 'Terms or phrases providing additional context for the resource.',
    'label': 'keyword'},
   'equivalent_properties': []},
  {'name': 'contact',
   'domain': ['AIResource'],
   'range': ['Person'],
   'annotations': {'comment': 'A contact person for acquiring information on the resource.',
    'label': 'contact'},
   'equivalent_properties': []},
  {'name': 'has_part',
   'domain': ['AIResource'],
   'range': ['AIResource'],
   'annotations': {'comment': 'A resource that includes this resource.',
    'label': 'has part'},
   'equivalent_properties': []},
  {'name': 'alternate_name',
   'domain': ['AIResource'],
   'range': ['str'],
   'annotations': {'comment': 'An alternative name commonly used for the resource in place of its name.',
    'label': 'alternative name'},
   'equivalent_properties': []}],
 'inherited_properties': [{'name': 'relevant_link',
   'domain': ['AIoDConcept'],
   'range': [],
   'annotations': {'comment': 'A web address where is a relevant resource related to the Entity.',
    'label': 'relevant link'},
   'equivalent_properties': [],
   'inherited_from': 'AIoDConcept'},
  {'name': 'identifier',
   'domain': ['AIoDConcept'],
   'range': ['int'],
   'annotations': {'comment': 'A unique identifier for the Entity.',
    'label': 'identifier'},
   'equivalent_properties': [],
   'inherited_from': 'AIoDConcept'},
  {'name': 'sameAs',
   'domain': ['AIoDConcept'],
   'range': ['AIoDConcept'],
   'annotations': {'comment': 'An equivalence relationship between entities.',
    'label': 'same as'},
   'equivalent_properties': [],
   'inherited_from': 'AIoDConcept'}]}